# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='childrens',
            field=models.ManyToManyField(blank=True, null=True, related_name='_event_childrens_+', to='event.Event', verbose_name='Возможные следствия'),
        ),
    ]
